### ISSUE TITLE
Error 10038

### ISSUE THREAD

**Issue by ErMutanda20** [Woahai321/soluify-telegram-copypaste-bot#1]
I am having an issue where, after setting everything up and starting up the bot I get the following message:

Successfully connected to Telegram!
[2024-08-22 23:03:16] Soluify is on the lookout for new messages... 👀
Type 'exit' and press Enter to stop forwarding and return to the main menu.
2024-08-22 23:03:16,847 - soluify - ERROR - Unexpected error: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket
Unexpected twist in our adventure: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket. Let's regroup and try again!  

The error 10038 is described in italian but it means Socket operation on nonsocket. 

I have 4GB of RAM, CPU: Intel(R) Pentium(R) Silver N5030 CPU @ 1.10GHz, I have Windows 11 64 bit as operating system and a 118 GB HDD.

As requested I have copy pasted below my terminal.
After inserting cd soluify-telegram-copypaste-bot and python SoluifyCopier.py that's what goes on:

_____  ___   _      __ __  ____  _____  __ __
 / ___/ /   \ | T    |  T  Tl    j|     ||  T  T
(   \_ Y     Y| |    |  |  | |  T |   __j|  |  |
 \__  T|  O  || l___ |  |  | |  | |  l_  |  ~  |
 /  \ ||     ||     T|  :  | |  | |   _] l___, |
 \    |l     !|     |l     | j  l |  T   |     !
  \___j \___/ l_____j \__,_j|____jl__j   l____/

   ___                          ___              _
  / __\  ___   _ __   _   _    / _ \  __ _  ___ | |_   ___
 / /    / _ \ | '_ \ | | | |  / /_)/ / _` |/ __|| __| / _ \
/ /___ | (_) || |_) || |_| | / ___/ | (_| |\__ \| |_ |  __/
\____/  \___/ | .__/  \__, | \/      \__,_||___/ \__| \___|
              |_|     |___/

Welcome to the Soluify Telegram Copy & Paste Bot!
====================================================
1. Log in with your API details (securely, of course!)
2. List all your Telegram chat IDs. (Note your source and destination IDs)
3. Set up the bot with the provided prompts.
4. Add custom filters and signatures to your messages.
5. Sit back and let us handle the rest!

Enter your password to decrypt credentials:
Credentials successfully decrypted! Welcome back! 🎉

What's your mission for today? 🕵️
1. List My Chat IDs 📋
2. Set Up Message Forwarding ⚙️
3. Edit Profile ✏️
4. Help ❓
5. Exit 👋
Pick your adventure (1-5): 2
Do you want to use a saved profile? (y/n): y
Available profiles: 🎭
1. Test 1
2. Test 2
Enter the profile number: 1
Preparing the message wormhole 💡
Successfully connected to Telegram! ✅
[2024-08-24 12:33:04] Soluify is on the lookout for new messages... 👀
Type 'exit' and press Enter to stop forwarding and return to the main menu.
2024-08-24 12:33:04,881 - soluify - ERROR - Unexpected error: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket
Unexpected twist in our adventure: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket. Let's regroup and try again!

I tried reeboting and changing network, tried no to use a profile and tried to create second one. I tried with multiple chats and nothing worked

**Comment by Woahai321** [comment]
Hi, thanks for raising this as an issue.

It looks like you're experiencing a socket-related issue. Lets first explain what a socket is and why it might be causing problems.

### What is a Socket?

A socket is an endpoint for sending or receiving data across a computer network. It's a fundamental technology used for communication between devices on a network, including the Internet. Sockets are used in various network protocols, including TCP/IP, which is the backbone of the Internet.

### Common Socket Issues

Sometimes, sockets can encounter problems such as being closed unexpectedly or becoming invalid. This can happen for various reasons, including network instability, resource limitations, or issues within the application itself.

### Troubleshooting Steps

Let's go through a few steps to troubleshoot and hopefully resolve the problem:

1. **Verify Active Connections**:
   - **Why?**: Sometimes, lingering connections can cause socket issues.
   - **How?**: Restart your computer to clear any existing socket connections that might be causing the issue.

2. **Update Telethon**:
   - **Why?**: Updating to the latest version can fix known issues and improve compatibility.
   - **How?**:
     ```sh
     pip install --upgrade telethon
     ```

3. **Run with Elevated Privileges**:
   - **Why?**: Running your script with administrative privileges can sometimes resolve permission-related socket issues.
   - **How?**: Right-click on your terminal or command prompt and select "Run as administrator."

4. **Check Firewall/Antivirus Settings**:
   - **Why?**: Firewalls and antivirus software can block or interfere with socket connections.
   - **How?**: Ensure that your firewall or antivirus is not blocking the Python executable. You might need to whitelist it or temporarily disable the firewall/antivirus to see if it resolves the issue.

Please try these steps and let me know any change in behaviour.

**Comment by ErMutanda20** [comment]
Hey, thanks for the in depth reply. Sadly after having tried all of these steps multiple times I have to say that none of this fixed my issue. I still get the same error 10038. 
Please let me know if I can try anything else

**Comment by Woahai321** [comment]
Hey, 

Can you please try running this on a different machine or configure a VM for testing?

It sounds like a device issue, i am unable to replicate the issue you are facing.

**Comment by Woahai321** [comment]
Hello! 👋

It’s been a while since we last heard from you—nearly 30 days! Just a quick heads-up that we’ll be **closing this issue in 5 days** if no further activity or response is received. 

If you're still having trouble or need additional assistance, feel free to leave a comment and we'll be happy to help out!
