### ISSUE TITLE
Symbols in pydroid 3

### ISSUE THREAD

**Issue by nebanti** [Woahai321/soluify-telegram-copypaste-bot#5]
Hello, I have lost the ability to run via PC. Is there an option to run pydroid. But it has a problem with symbols. Is there any way to fix this? For example: 

Do you ┬␋⎽# ├⎺ ⎽▒┴␊ ≤⎺┤⎼ ┌⎺±␋┼ ␌⎼␊␍␊┼├␋▒┌⎽ °⎺⎼ °┤├┤⎼␊ ┤⎽␊ (⎽├▒≤ ⎽␋±┼␊␍ ␋┼)? (≤/┼):
F⎼⎺└ ▒ ⎽␊␌┤⎼␋├≤ ⎻␊⎼⎽⎻␊␌├␋┴␊◀ ⎽▒┴␋┼± ␌⎼␊␍␊┼├␋▒┌⎽ ␋⎽ ┼⎺├ ⎼␊␌⎺└└␊┼␍␊␍▼ ⚠️
C⎼␊␍␊┼├␋▒┌⎽ ┬␋┌┌ ┼⎺├ ␉␊ ⎽▒┴␊␍▼ T#␊≤ ┬␋┌┌ ␉␊ ␍␊┌␊├␊␍ ┬#␊┼ ≤⎺┤ ␊│␋├ ├#␊ ⎽␌⎼␋⎻├▼
E┼├␊⎼ ≤⎺┤⎼ ⎻▒⎽⎽┬⎺⎼␍ ├⎺ ␍␊␌⎼≤⎻├ ␌⎼␊␍␊┼├␋▒┌⎽:
C⎼␊␍␊┼├␋▒┌⎽ ⎽┤␌␌␊⎽⎽°┤┌┌≤ ␍␊␌⎼≤⎻├␊␍! W␊┌␌⎺└␊ ␉▒␌┐! 🎉

W#▒├'⎽ ≤⎺┤⎼ └␋⎽⎽␋⎺┼ °⎺⎼ ├⎺␍▒≤? 🕵️
1▼ L␋⎽├ M≤ C#▒├ ID⎽ 📋
2▼ S␊├ U⎻ M␊⎽⎽▒±␊ F⎺⎼┬▒⎼␍␋┼± ⚙️
3▼ E␍␋├ P⎼⎺°␋┌␊ ✏️
4▼ H␊┌⎻ ❓
5▼ E│␋├ 👋
Enter k␊≤┬⎺⎼␍⎽ ├⎺ °␋┌├␊⎼ └␊⎽⎽▒±␊⎽ (⎺⎻├␋⎺┼▒┌)▼ L␊▒┴␊ ␉┌▒┼┐ ├⎺ °⎺⎼┬▒⎼␍ ▒┌┌ └␊⎽⎽▒±␊⎽:
E┼├␊⎼ ├#␊ ⎽␋±┼▒├┤⎼␊ ├⎺ ▒⎻⎻␊┼␍ ├⎺ ␊▒␌# └␊⎽⎽▒±␊:
E┼├␊⎼ ␉┌▒␌┐┌␋⎽├␊␍ ┬⎺⎼␍⎽ (␌⎺└└▒ ⎽␊⎻▒⎼▒├␊␍◀ ⎺⎼ ┌␊▒┴␊ ␉┌▒┼┐):
D⎺ ≤⎺┤ ┬▒┼├ ├⎺ ⎽▒┴␊ ├#␋⎽ ␌⎺┼°␋±┤⎼▒├␋⎺┼ ▒⎽ ▒ ⎻⎼⎺°␋┌␊? (≤/┼):
P⎼␊⎻▒⎼␋┼± ├#␊ └␊⎽⎽▒±␊ ┬⎺⎼└#⎺┌␊ 💡
S┤␌␌␊⎽⎽°┤┌┌≤ ␌⎺┼┼␊␌├␊␍ ├⎺ T␊┌␊±⎼▒└! ✅
[2█24▲1█▲28 18:█4:11] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:16] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:21] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:26] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:32] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:37] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼
[2█24▲1█▲28 18:█4:42] S⎺┌┤␋°≤ ␋⎽ ⎺┼ ├#␊ ┌⎺⎺┐⎺┤├ °⎺⎼ ┼␊┬ └␊⎽⎽▒±es... 👀
Type 'exit' and press Enter to stop forwarding and return to the main └␊┼┤▼

**Comment by Woahai321** [comment]
Hi, unfortunately we will not be adding support for pydroid.
